CREATE TABLE MEMBER(
	ID VARCHAR2(30 BYTE) primary key, 
	name VARCHAR2(20 BYTE), 
	PHONE VARCHAR2(20 BYTE), 
	PASSWORD VARCHAR2(60 BYTE), 
	NICKNAME VARCHAR2(20 BYTE), 
	AUTHORITY VARCHAR2(50 BYTE), 
	ENABLED NUMBER(1,0), 
	REGDATE DATE
);


CREATE TABLE STORE() 
    STORENO NUMBER PRIMARY KEY , 
	ID VARCHAR2(30 BYTE), 
	STORENAME VARCHAR2(20 BYTE), 
	PHOTO VARCHAR2(500 BYTE), 
	LOCATION VARCHAR2(30 BYTE), 
	CATEGORY VARCHAR2(30 BYTE), 
	STORE_PHONE VARCHAR2(20 BYTE), 
	PARKING VARCHAR2(10 BYTE), 
	HOLYDAY VARCHAR2(20 BYTE), 
	INTRODUCE VARCHAR2(500 BYTE), 
	NOTICE VARCHAR2(500 BYTE), 
	FOREIGN KEY (ID)  REFERENCES MEMBER(ID)
)

CREATE TABLE REVIEW(
	REVIEWNO NUMBER PRIMARY KEY, 
	RATING NUMBER(*,2) NOT NULL, 
	ID VARCHAR2(30 BYTE) NOT NULL, 
	STORENO NUMBER NOT NULL, 
	REVIEWPHOTO VARCHAR2(500 BYTE), 
	REVIEWCONTENT VARCHAR2(100 BYTE) NOT NULL, 
	REVIEWRDATE DATE NOT NULL , 
	FOREIGN KEY (STORENO)  REFERENCES STORE(STORENO) ON DELETE CASCADE
)

CREATE TABLE SERVICEBOARD( 
	SERVICENO NUMBER PRIMARY KEY, 
	ID VARCHAR2(30 BYTE), 
	TITLE VARCHAR2(20 BYTE), 
	CONTENT VARCHAR2(500 BYTE), 
	VIEWS NUMBER, 
	REGDATE DATE, 
  	 FOREIGN KEY (ID) REFERENCES MEMBER(ID) 
   )
   
CREATE TABLE REVIEWLIKE( 
	REVIEWLIKENO NUMBER PRIMARY KEY, 
	STORENO NUMBER(*,0) NOT NULL , 
	ID VARCHAR2(30 BYTE) NOT NULL , 
 	FOREIGN KEY (STORENO)  REFERENCES STORE(STORENO) ON DELETE CASCADE, 
 	FOREIGN KEY (ID) REFERENCES MEMBER(ID)
 )

CREATE TABLE REVIEWCOMMENT( 
	REVIEWCOMMENTNO NUMBER PRIMARY KEY , 
	REVIEWNO NUMBER NOT NULL , 
	ID VARCHAR2(30 BYTE) NOT NULL, 
	REVIEWCOMMENTCONTENT VARCHAR2(500 BYTE) NOT NULL, 
	REVIEWCOMMENTRDATE DATE NOT NULL ENABLE, 
	FOREIGN KEY (REVIEWNO) REFERENCES REVIEW(REVIEWNO) ON DELETE CASCADE, 
	FOREIGN KEY (ID) REFERENCES MEMBER(ID)
  )
 
CREATE TABLE RESERVEPOSSIBLE(
	STORENO NUMBER, 
	DAY DATE, 
	TIME VARCHAR2(50 BYTE), 
	CAPACITY NUMBER, 
	SEAT NUMBER, 
	 FOREIGN KEY (STORENO) REFERENCES STORE(STORENO)
)

CREATE TABLE RESERVATION( 
    RESERVENO NUMBER PRIMARY KEY, 
	ID VARCHAR2(30 BYTE), 
	STORENO NUMBER, 
	PEOPLE NUMBER, 
	VISITDAY DATE, 
	VISITTIME VARCHAR2(100 BYTE), 
	VISITNAME VARCHAR2(20 BYTE), 
	VISITPHONE VARCHAR2(20 BYTE), 
	REGDATE DATE, 
	 FOREIGN KEY (ID) REFERENCES MEMBER(ID), 
	 FOREIGN KEY (STORENO) REFERENCES STORE(STORENO)
   ) 
  
  CREATE TABLE REPLY(
    REPLYNO NUMBER PRIMARY KEY, 
	SERVICENO NUMBER, 
	ID VARCHAR2(30 BYTE), 
	ANSWER VARCHAR2(500 BYTE), 
	REGDATE DATE, 
	FOREIGN KEY (ID)  REFERENCES MEMBER(ID),
	FOREIGN KEY (SERVICENO) REFERENCES SERVICEBOARD(SERVICENO) ON DELETE CASCADE
   )

CREATE TABLE MENU( 
    MENUNAME VARCHAR2(50 BYTE) PRIMARY KEY, 
	STORENO NUMBER, 
	PRICE NUMBER, 
	MENUINFO VARCHAR2(100 BYTE), 
	MENUPHOTO VARCHAR2(500 BYTE), 
	ORDERNO NUMBER, 
	FOREIGN KEY (STORENO) REFERENCES STORE(STORENO)
)   